### ISSUE TITLE
First issues

### ISSUE THREAD

**Issue by arcaldwell49** [arcaldwell49/cik-quarto#2]
Changing aspect ratio when resizing figures in PDF: Resizing large figures with out.width="100%" works, but changes the aspect ratio (see the PDF). This should be related to the template, as normal Quarto pdf rendering does the resizing automatically while keeping the aspect ratio.
    Cross-referencing in PDF: I tried to do cross-referencing for figures and tables in html and pdf. This requires both html and pdf output to be generated within a single chunk, but that worked for me. I tried to rely on the native Quarto cross-referencing system, which should automatically add something like Figure 1: before the caption. This worked for html, but not for pdf (still the cross-referencing itself did work, just not the automatic caption generation). One could use a workaround, with generating different captions for html (only caption) and pdf ("Figure X:" + caption) with an !expr if (knitr::is_htlm_output()) statement in the chunk options, but as this problem does not occur in normal Quarto pdf rendering, i believe it is better to try to make changes to the template. In the medium term, we could try to get rid of using chunks at all to generate figures with using the default-image-extension YAML option (https://quarto.org/docs/authoring/figures.html#multiformat-figures), assuming that both pdf and html images have the same caption.

**Comment by arcaldwell49** [comment]
@smnnlt Working on the first issue in the original message

The second issue is on purpose. I've run into issues with the internal numbering system before and prefer to just add the labeling/referencing system manually to avoid some annoying issues.

**Comment by smnnlt** [comment]
Hi @arcaldwell49,

Figure resizing now works for me, thank you for fixing this! 

Regarding the figure and table labeling I suggest giving Quarto's auto-labelling a try. At the moment the auto-labeling does work for html but not for pdf, and thus requires different captions for the different format. This is somewhat annoying as it requires code execution in the `fig-cap` chunk options (two different chunks are not possible, because this would break the cross-referencing).
